Repository InternetHealthReport/ihr-website, pull requests merged in 2024-03, with the labels that each got.

#761 Added cookie feature
  src/App.vue
  src/components/CookieBanner.vue
  src/i18n/translation.js
Labels: enhancement

#760 upgrading the searchbar to select country through a world-map
  src/components/Header.vue
  src/components/maps/WorldMap.vue
  src/components/search/SearchBar.vue
Labels: enhancement

#763 Fixes Based on IYP Integration Feedback
  package.json
  src/components/charts/NetworkDelayChart.vue
  src/components/iyp/as/ASConnectedASes.vue
  src/components/iyp/as/ASPopularHostNames.vue
  src/components/iyp/prefix/PrefixPopularHostNames.vue
  src/components/iyp/tag/TagPopularHostNames.vue
  src/components/tables/IypGenericTable.vue
Labels: bug

#766 Add Local Caching, Fix Typo, and Rename Banner for Local Storage
  package.json
  src/App.vue
  src/components/CookieBanner.vue
  src/components/LocalStorageBanner.vue
  src/components/networks/as/ASOverview.vue
  src/i18n/translation.js
  src/plugins/IypApi.js
  src/plugins/cache.js
Labels: enhancement

#767 Add observable notebooks
  package.json
  src/App.vue
  src/components/Footer.vue
  src/components/Header.vue
  src/components/LocalStorageBanner.vue
  src/components/charts/AsInterdependenciesChart.vue
  src/components/charts/DelayAndForwardingChart.vue
  src/components/charts/NetworkDelayChart.vue
  src/components/networks/as/ASCustom.vue
  src/components/networks/as/ASOverview.vue
  src/components/networks/country/CountryCustom.vue
  src/components/networks/country/CountryOverview.vue
  src/components/networks/prefix/PrefixOverview.vue
  src/components/networks/tag/TagOverview.vue
  src/i18n/locales/en.json
  src/i18n/locales/jp.json
  src/plugins/cache.js
  src/plugins/layouts/layoutsChart.js
  src/plugins/models/IodaChartDataModel.js
  src/router/index.js
  src/views/Observable.vue
Labels: bug, enhancement

#769 User Info UI
  src/components/UserInfo.vue
  src/plugins/RipeApi.js
  src/views/Home.vue
Labels: enhancement

#771 Fix for PR `#769`
  package.json
  src/components/UserInfo.vue
  src/views/Home.vue
Labels: bug, css

#775 Peeringdb fix
  src/components/networks/as/ASOverview.vue
  src/components/networks/ixp/IXPOverview.vue
Labels: bug

#774 Fix cache in errors and timeouts & change routes
  index.html
  src/components/Footer.vue
  src/components/Header.vue
  src/components/UserInfo.vue
  src/components/iyp/as/ASOriginatedPrefixes.vue
  src/components/iyp/country/CountryIPPrefixes.vue
  src/components/iyp/hostName/HostNameAuthoritativeNameservers.vue
  src/components/iyp/hostName/HostNameIPAddressesPrefixes.vue
  src/components/networks/AS.vue
  src/components/networks/Country.vue
  src/components/networks/HostName.vue
  src/components/networks/IXP.vue
  src/components/networks/Prefix.vue
  src/components/networks/Rank.vue
  src/components/networks/Tag.vue
  src/components/networks/as/ASOverview.vue
  src/components/networks/country/CountryOverview.vue
  src/components/networks/ixp/IXPOverview.vue
  src/components/networks/prefix/PrefixOverview.vue
  src/components/search/SearchBar.vue
  src/components/tables/AggregatedAlarmsTable.vue
  src/components/tables/AsInterdependenciesTable.vue
  src/components/tables/CountryHegemonyTable.vue
  src/components/tables/DelayAlarmsTable.vue
  src/components/tables/DiscoAlarmsTable.vue
  src/components/tables/IypGenericTable.vue
  src/components/tables/NetworkDelayAlarmsTable.vue
  src/components/tables/PrefixHegemonyTable.vue
  src/components/tables/PrefixHegemonyTableStats.vue
  src/i18n/translation.js
  src/plugins/IypGenericTreemapChart.js
  src/plugins/cache.js
  src/router/index.js
  src/views/Countries.vue
  src/views/Home.vue
  src/views/HostNames.vue
  src/views/MetisDeployment.vue
  src/views/Networks.vue
  src/views/Ranks.vue
  src/views/Tags.vue
Labels: bug
